### ISSUE TITLE
😫 Service Worker is registered, but never seems to install?

### ISSUE THREAD

**Issue by lewiscowper** [lewiscowper/serviceworker-react#2]
Navigating to http://lewiscowper.github.io/serviceworker-react/ with a serviceworker enabled browser, manages to console.log the registration of the serviceworker 'sw.js' within the main scope of http://lewiscowper.github.io/serviceworker-react/.

This is :+1:

However, I can't seem to get the serviceworker to do anything in the sw.js file I have. I'm not sure whether it's where I have 'sw.js' or whether it's something internal. Whatever it is, it's failing silently, and I can't figure it out.

**Comment by KenjiBaheux** [comment]
@lewiscowper The registration is actually failing. In the oninstall event handler, you are using cache.addAll which fails because this method is currently not supported in Chrome. DevTools should provide enough information to let you find this on your own though (will follow-up with the team).

In the meantime, we still recommend to use the cache polyfill to complete the native implementation.

Here is the relevant excerpt from the [HTML5Rocks article](http://www.html5rocks.com/en/tutorials/service-worker/introduction/):

>Grab the caches polyfill from this repository https://github.com/coonsta/cache-polyfill.
>
>This polyfill will add support for CacheStorage.match, Cache.add and Cache.addAll which Chrome M40's implementation of the Cache API doesn't currently support.
>
>Grab dist/serviceworker-cache-polyfill.js to put somewhere in your site and use it in a service worker with the importScripts method. Any script which is imported will automatically be cached by the service worker.
>
>```importScripts('serviceworker-cache-polyfill.js');```

cc/ @gavinp @inexorabletash

**Comment by jakearchibald** [comment]
Ah, @KenjiBaheux beat me to it!

In `chrome://serviceworker-internals/`, "Open DevTools window and pause…" is really useful for catching these startup bugs.
